import showChessBoard from './src/task1.js';
import analyzeEnvelopes from './src/task2.js';
import makeTrianglesSorting from './src/task3.js';
import getPalindrome from './src/task4.js';
import luckyTicketCounting from './src/task5.js';
import numericSequence from './src/task6.js';
import { getFibonacci } from './src/task7.js';
import checkParamTask1 from './src/components/checkParamTask1.js';
import checkParamTask2 from './src/components/checkParamTask2.js';
import checkParamTask3 from './src/components/checkParamTask3.js';
import checkParamTask4 from './src/components/checkParamTask4.js';
import checkParamTask5 from './src/components/checkParamTask5.js';
import checkParamTask6 from './src/components/checkParamTask6.js';
import checkParamTask7 from './src/components/checkParamTask7.js';
import createChess from './src/DOM/chess.js';
import showAnalyzeEnvelopes from './src/DOM/analyzeEnvelopes.js';
import showTrianglesSort from './src/DOM/trianglesSort.js';
import showPalindrome from './src/DOM/showPalindrome.js';
import showLuckyTickets from './src/DOM/showLuckyTickets.js';
import showSequence from './src/DOM/showSequence.js';
import { showFibLength, showFibRange } from './src/DOM/fibonacci.js';
import makeTabs from './src/aux/tabs.js';
import clearInputs from './src/aux/clearAllInputs.js';
import createNotification from './src/aux/createNotification.js';
import getElem from './src/aux/getElem.js';
export { createNotification, getElem };

export { checkParamTask1, showChessBoard };
export { checkParamTask2, analyzeEnvelopes };
export { checkParamTask3, makeTrianglesSorting };
export { checkParamTask4, getPalindrome };
export { checkParamTask5, luckyTicketCounting };
export { checkParamTask6, numericSequence };
export { checkParamTask7, getFibonacci };

getElem('.btnChess').addEventListener('click', createChess);
getElem('.btnAnalyse').addEventListener('click', showAnalyzeEnvelopes);
getElem('.btnFibLength').addEventListener('click', showFibLength);
getElem('.btnFibMinMax').addEventListener('click', showFibRange);
getElem('.btnTickets').addEventListener('click', showLuckyTickets);
getElem('.btnPalindrome').addEventListener('click', showPalindrome);
getElem('.btnSequence').addEventListener('click', showSequence);
getElem('.btnGetSort').addEventListener('click', showTrianglesSort);
